# Generated by Django 5.2.4 on 2025-07-22 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0005_page_competence_generale_page_couleur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Titre de la séquence pédagogique', max_length=255, verbose_name='Nom de la séquence')),
                ('description', models.TextField(blank=True, help_text='Description détaillée de la séquence et de ses objectifs', verbose_name='Description')),
                ('niveau', models.CharField(blank=True, choices=[('PS', 'PS - Petite Section'), ('MS', 'MS - Moyenne Section'), ('GS', 'GS - Grande Section'), ('CP', 'CP - Cours Préparatoire'), ('CE1', 'CE1 - Cours Élémentaire 1'), ('CE2', 'CE2 - Cours Élémentaire 2'), ('CM1', 'CM1 - Cours Moyen 1'), ('CM2', 'CM2 - Cours Moyen 2'), ('6eme', '6ème - Sixième'), ('5eme', '5ème - Cinquième'), ('4eme', '4ème - Quatrième'), ('3eme', '3ème - Troisième')], help_text='Niveau scolaire visé par cette séquence', max_length=10, verbose_name='Niveau de classe')),
                ('duree_estimee', models.PositiveIntegerField(blank=True, help_text='Nombre de séances prévues pour cette séquence', null=True, verbose_name='Durée estimée (séances)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans la liste des séquences", verbose_name="Ordre d'affichage")),
                ('discipline', models.ForeignKey(help_text='Discipline à laquelle appartient cette séquence', limit_choices_to={'parent__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='pages.page', verbose_name='Discipline')),
                ('user', models.ForeignKey(help_text='Enseignant qui a créé cette séquence', on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Séquence pédagogique',
                'verbose_name_plural': 'Séquences pédagogiques',
                'ordering': ['discipline', 'ordre', 'name'],
                'unique_together': {('user', 'name', 'discipline')},
            },
        ),
    ]
