# Generated by Django 5.2.4 on 2025-07-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='total_duration_minutes',
            field=models.IntegerField(default=0, help_text='Durée totale calculée automatiquement à partir de toutes les séances de la séquence', verbose_name='Durée totale en minutes'),
        ),
    ]
