# Generated by Django 5.2.4 on 2025-07-28 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0002_sequence_total_duration_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Période 1 - Rentrée scolaire', max_length=100, verbose_name='Nom de la période')),
                ('numero', models.IntegerField(choices=[(1, 'Période 1 - Septembre/Octobre'), (2, 'Période 2 - Novembre/Décembre'), (3, 'Période 3 - Janvier/Février'), (4, 'Période 4 - Mars/Avril'), (5, 'Période 5 - Mai/Juin/Juillet')], help_text='Numéro de la période (1 à 5)', verbose_name='Numéro de période')),
                ('date_debut', models.DateField(help_text='Date de début de la période', verbose_name='Date de début')),
                ('date_fin', models.DateField(help_text='Date de fin de la période', verbose_name='Date de fin')),
                ('annee_scolaire', models.CharField(help_text='Ex: 2024-2025', max_length=9, verbose_name='Année scolaire')),
                ('description', models.TextField(blank=True, help_text='Description optionnelle de la période (thèmes, projets...)', verbose_name='Description')),
                ('couleur', models.CharField(default='#3498db', help_text="Couleur d'affichage de la période (format hex: #RRGGBB)", max_length=7, verbose_name='Couleur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes_scolaires', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Période scolaire',
                'verbose_name_plural': 'Périodes scolaires',
                'ordering': ['annee_scolaire', 'numero'],
                'unique_together': {('user', 'annee_scolaire', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='sequence',
            name='periode_scolaire',
            field=models.ForeignKey(blank=True, help_text="Période scolaire dans laquelle s'inscrit cette séquence", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequences', to='sequences.periodescolaire', verbose_name='Période scolaire'),
        ),
    ]
