# Generated by Django 5.2.4 on 2025-08-07 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_pageannexe'),
        ('sequences', '0003_periodescolaire_sequence_periode_scolaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='discipline',
            field=models.ForeignKey(blank=True, help_text='Discipline à laquelle appartient cette séquence (optionnel)', limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='pages.page', verbose_name='Discipline'),
        ),
    ]
