# Generated by Django 5.2.4 on 2025-07-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_fiche'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fiche',
        ),
    ]
