# Generated by Django 4.2.23 on 2025-07-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_delete_fiche'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='competence_generale',
            field=models.TextField(blank=True, null=True, verbose_name='Compétence générale'),
        ),
        migrations.AddField(
            model_name='page',
            name='couleur',
            field=models.CharField(blank=True, help_text="Couleur hexadécimale (ex: #0d6efd). S'applique aux enfants.", max_length=7, null=True, verbose_name='Couleur de la discipline'),
        ),
        migrations.AddField(
            model_name='page',
            name='cycle_enseignement',
            field=models.CharField(blank=True, choices=[('cycle_1', 'Cycle 1'), ('cycle_2', 'Cycle 2'), ('cycle_3', 'Cycle 3')], max_length=10, null=True, verbose_name="Cycle d'enseignement"),
        ),
        migrations.AddField(
            model_name='page',
            name='objectifs_generaux',
            field=models.TextField(blank=True, null=True, verbose_name='Objectifs généraux'),
        ),
    ]
