# Generated by Django 5.2.4 on 2025-08-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_competence_generale_page_couleur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
