# Generated by Django 5.2.4 on 2025-08-05 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_page_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAnnexe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'annexe")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('fichier', models.FileField(upload_to='pages/annexes/', verbose_name='Fichier')),
                ('type_fichier', models.CharField(blank=True, max_length=50, verbose_name='Type de fichier')),
                ('taille_fichier', models.PositiveIntegerField(default=0, verbose_name='Taille en octets')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annexes', to='pages.page', verbose_name='Compétence')),
            ],
            options={
                'verbose_name': 'Annexe de compétence',
                'verbose_name_plural': 'Annexes de compétences',
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
    ]
