# Generated by Django 5.2.4 on 2025-08-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_accessories',
            field=models.CharField(choices=[('none', 'Aucun'), ('glasses', 'Lunettes'), ('hat', 'Chapeau'), ('earrings', "Boucles d'oreilles")], default='none', help_text='Accessoires', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_clothing_color',
            field=models.CharField(default='#2E86AB', help_text='Couleur des vêtements (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_eye_color',
            field=models.CharField(default='#4A90E2', help_text='Couleur des yeux (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_hair_color',
            field=models.CharField(default='#8B4513', help_text='Couleur des cheveux (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_hair_style',
            field=models.CharField(choices=[('short', 'Cheveux courts'), ('medium', 'Cheveux mi-longs'), ('long', 'Cheveux longs'), ('curly', 'Cheveux bouclés'), ('bald', 'Chauve')], default='short', help_text='Style de cheveux', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_skin_color',
            field=models.CharField(default='#FDBCB4', help_text='Couleur de peau (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_type',
            field=models.CharField(choices=[('bitmoji', 'Bitmoji (import)'), ('generated', 'Avatar généré')], default='generated', help_text="Type d'avatar utilisé", max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bitmoji_url',
            field=models.URLField(blank=True, help_text="URL du Bitmoji de l'utilisateur (obsolète)", max_length=500, null=True),
        ),
    ]
