# Generated by Django 5.2.4 on 2025-07-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0001_initial'),
        ('pages', '0004_delete_fiche'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='competences',
            field=models.ManyToManyField(blank=True, related_name='fiches_associees', to='pages.page'),
        ),
    ]
