# Generated by Django 5.2.4 on 2025-07-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0002_fiche_competences'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
