# Generated by Django 5.2.4 on 2025-07-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0003_fiche_date_fiche_heure_debut_fiche_heure_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiche',
            name='competences',
        ),
        migrations.AlterField(
            model_name='fiche',
            name='date',
            field=models.DateField(),
        ),
    ]
