# Generated by Django 5.2.4 on 2025-07-10 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0004_remove_fiche_competences_alter_fiche_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
