# Generated by Django 4.2.23 on 2025-07-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0007_fiche_attendus_fiche_bilan_fiche_criteres_evaluation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiche',
            name='attendus',
        ),
        migrations.RemoveField(
            model_name='fiche',
            name='contenu',
        ),
        migrations.RemoveField(
            model_name='fiche',
            name='criteres_evaluation',
        ),
        migrations.RemoveField(
            model_name='fiche',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='fiche',
            name='domaine',
        ),
        migrations.RemoveField(
            model_name='fiche',
            name='objectif',
        ),
        migrations.RemoveField(
            model_name='fiche',
            name='seance',
        ),
    ]
