# Generated by Django 4.2.23 on 2025-07-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0008_remove_fiche_attendus_remove_fiche_contenu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='couleur',
            field=models.CharField(blank=True, help_text='Code hexadécimal de la couleur (ex: #ff0000 pour rouge)', max_length=7),
        ),
    ]
