# Generated by Django 5.2.4 on 2025-07-15 19:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0009_fiche_couleur'),
        ('pages', '0005_page_competence_generale_page_couleur_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiche',
            options={'ordering': ['-date', 'titre'], 'verbose_name': 'Fiche de préparation', 'verbose_name_plural': 'Fiches de préparation'},
        ),
        migrations.AddField(
            model_name='fiche',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 15, 21, 46, 4, 362944)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiche',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='bilan',
            field=models.TextField(blank=True, verbose_name='Bilan de la séance'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='competences',
            field=models.ManyToManyField(blank=True, related_name='fiches_competences', to='pages.page', verbose_name='Compétences associées'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='couleur',
            field=models.CharField(blank=True, help_text='Code hexadécimal (ex: #ff0000)', max_length=7, verbose_name='Couleur de la discipline'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches', to='pages.page', verbose_name='Discipline'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='duree',
            field=models.CharField(blank=True, max_length=50, verbose_name='Durée (calculée ou manuelle)'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de début'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de fin'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='niveau',
            field=models.CharField(blank=True, max_length=255, verbose_name='Niveau de classe'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='sequence',
            field=models.CharField(blank=True, max_length=255, verbose_name='Séquence'),
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=255, verbose_name='Nom de la phase')),
                ('duree', models.CharField(blank=True, max_length=50, verbose_name='Durée')),
                ('ce', models.CharField(blank=True, max_length=255, verbose_name='Compétence évaluée')),
                ('deroulement', models.TextField(blank=True, verbose_name='Déroulement de la phase')),
                ('posture', models.CharField(blank=True, max_length=255, verbose_name="Posture de l'enseignant")),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='fiches.fiche', verbose_name='Fiche de préparation')),
            ],
            options={
                'verbose_name': 'Phase',
                'verbose_name_plural': 'Phases',
                'ordering': ['ordre'],
            },
        ),
    ]
