# Generated by Django 5.2.4 on 2025-07-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0010_alter_fiche_options_fiche_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='deroulement',
            field=models.TextField(blank=True, verbose_name='Déroulement de la phase'),
        ),
    ]
