# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0011_alter_phase_deroulement'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Indique si la séance a été réalisée', verbose_name='Séance réalisée'),
        ),
        migrations.AddField(
            model_name='fiche',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Date et heure de validation de la réalisation', null=True, verbose_name='Validée le'),
        ),
    ]
