# Generated by Django 5.2.4 on 2025-07-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0011_alter_phase_deroulement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='niveau',
            field=models.CharField(blank=True, choices=[('PS', 'PS - Petite Section'), ('MS', 'MS - Moyenne Section'), ('GS', 'GS - Grande Section'), ('CP', 'CP - Cours Préparatoire'), ('CE1', 'CE1 - Cours Élémentaire 1'), ('CE2', 'CE2 - Cours Élémentaire 2'), ('CM1', 'CM1 - Cours Moyen 1'), ('6eme', '6ème - Sixième')], max_length=10, verbose_name='Niveau de classe'),
        ),
    ]
