# Generated by Django 5.2.4 on 2025-07-22 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0013_fiche_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='import_count',
            field=models.PositiveIntegerField(default=0, help_text="Nombre de fois que cette fiche a été importée par d'autres utilisateurs", verbose_name="Nombre d'importations"),
        ),
        migrations.AddField(
            model_name='fiche',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Permet aux autres utilisateurs de voir et importer cette fiche', verbose_name='Partagé avec la communauté'),
        ),
        migrations.AddField(
            model_name='fiche',
            name='original_author',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a créé la fiche originale (pour les fiches importées)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_fiches', to=settings.AUTH_USER_MODEL, verbose_name='Auteur original'),
        ),
        migrations.AddField(
            model_name='fiche',
            name='shared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de partage'),
        ),
    ]
