# Generated by Django 5.2.4 on 2025-07-22 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0014_fiche_import_count_fiche_is_shared_and_more'),
        ('sequences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='sequence_obj',
            field=models.ForeignKey(blank=True, help_text='Séquence pédagogique à laquelle appartient cette séance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='sequences.sequence', verbose_name='Séquence (objet)'),
        ),
    ]
