# Generated by Django 5.2.4 on 2025-07-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0015_fiche_sequence_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Durée calculée automatiquement à partir des heures de début et fin', null=True, verbose_name='Durée en minutes'),
        ),
    ]
