# Generated by Django 5.2.4 on 2025-08-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0012_add_completion_field'),
        ('fiches', '0016_fiche_duration_minutes'),
    ]

    operations = [
    ]
