# Generated by Django 5.2.4 on 2025-08-05 08:41

import django.db.models.deletion
import fiches.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0017_merge_20250804_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annexe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom descriptif de l'annexe", max_length=255, verbose_name="Nom de l'annexe")),
                ('fichier', models.FileField(help_text='Image (JPG, PNG, GIF) ou document PDF', upload_to=fiches.models.annexe_upload_path, verbose_name='Fichier')),
                ('type_fichier', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('document', 'Document')], max_length=20, verbose_name='Type de fichier')),
                ('taille_fichier', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille du fichier (bytes)')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('description', models.TextField(blank=True, help_text="Description optionnelle de l'annexe", verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annexes', to='fiches.fiche', verbose_name='Fiche de préparation')),
            ],
            options={
                'verbose_name': 'Annexe',
                'verbose_name_plural': 'Annexes',
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
    ]
