# Generated by Django 5.2.4 on 2025-08-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0018_annexe'),
    ]

    operations = [
    ]
