# Generated by Django 5.2.4 on 2025-08-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0019_auto_20250805_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='competencesSup',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fiche',
            name='groupes',
            field=models.CharField(blank=True, max_length=50, verbose_name='groupes'),
        ),
    ]
