# Generated by Django 5.2.4 on 2025-08-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0020_fiche_competencessup_fiche_groupes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='AFC',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fiche',
            name='objectifGeneral',
            field=models.CharField(blank=True, max_length=400, verbose_name='objectifGeneral'),
        ),
    ]
