# Generated by Django 5.2.4 on 2025-08-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0021_fiche_afc_fiche_objectifgeneral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='AFC',
            field=models.CharField(max_length=255),
        ),
    ]
