# Generated by Django 5.2.4 on 2025-08-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0022_alter_fiche_afc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='AFC',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='competencesSup',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
