# Generated by Django 5.2.4 on 2025-08-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0023_alter_fiche_afc_alter_fiche_competencessup'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='materiel',
            field=models.CharField(blank=True, max_length=250, verbose_name='materiel'),
        ),
    ]
