# Generated by Django 5.2.4 on 2025-08-05 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_emailvalidationtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('path', models.CharField(max_length=500, verbose_name="Chemin d'accès")),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='Méthode HTTP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('is_bot', models.BooleanField(default=False, verbose_name='Bot détecté')),
                ('is_suspicious', models.BooleanField(default=False, verbose_name='Activité suspecte')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur (si connecté)')),
            ],
            options={
                'verbose_name': "Log d'accès",
                'verbose_name_plural': "Logs d'accès",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', '-timestamp'], name='main_access_ip_addr_7b5587_idx'), models.Index(fields=['is_bot', '-timestamp'], name='main_access_is_bot_40f945_idx'), models.Index(fields=['is_suspicious', '-timestamp'], name='main_access_is_susp_220ed4_idx')],
            },
        ),
    ]
