# Generated by Django 5.2.4 on 2025-08-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_accesslog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailValidationToken',
        ),
    ]
